### ISSUE TITLE
Search Opportunity by most recent

### ISSUE THREAD

**Issue by jerradmonagan** [sp-curr-name/VMS-homework#4]
Need to add search for most recent to look for last 60 days. view is built but still need the algorithm.

**Comment by MichaelDimmitt** [comment]
@jerradmonagan, possibly this? sql statement.
<pre>SELECT DATEADD(d,-60,GETDATE())</pre>
https://www.sqlservercentral.com/Forums/Topic835159-23-1.aspx

**Comment by MichaelDimmitt** [comment]
@ckchessmaster, if database has date url.
```SELECT DATEADD(DAY,-60,GETDATE())```
https://stackoverflow.com/questions/16645973/how-to-select-data-from-30-days

**Comment by ckchessmaster** [comment]
I added functionality to search by last 60 days in my commit to the blow it up branch. The page needs to be prettied up a little bit though.

**Comment by jerradmonagan** [comment]
Fixed
